// Magik Terminal for Codex (By W1d0wm4k3r). MIT visual code.
// Generated by tools/build-macos-shader.py from windows/magik.hlsl.
// Logo dot data derives from Apache-2.0 Codex source; see assets/README.md.
// Ghostty supplies iChannel0, iResolution, iTime, and iCurrentCursor.
float saturate(float v) { return clamp(v, 0.0, 1.0); }
vec3 saturate(vec3 v) { return clamp(v, 0.0, 1.0); }
vec4 terminalAt(vec2 topUV) {
    return texture(iChannel0, vec2(topUV.x, 1.0 - topUV.y));
}
const uvec2 logoRows[54] = uvec2[54](
    uvec2(0u, 0u),
    uvec2(65011712u, 0u),
    uvec2(536608768u, 0u),
    uvec2(2147418112u, 0u),
    uvec2(4294934528u, 511u),
    uvec2(4294950912u, 2047u),
    uvec2(4269793280u, 4095u),
    uvec2(4228902912u, 8191u),
    uvec2(4261670912u, 16383u),
    uvec2(4286707712u, 32641u),
    uvec2(2145515520u, 65280u),
    uvec2(535885824u, 65024u),
    uvec2(134020864u, 130079u),
    uvec2(2214363072u, 129151u),
    uvec2(3774644192u, 129279u),
    uvec2(4168908768u, 127999u),
    uvec2(4231823344u, 131071u),
    uvec2(4282155000u, 131065u),
    uvec2(4294737400u, 131040u),
    uvec2(4294737148u, 130945u),
    uvec2(4294737148u, 130823u),
    uvec2(4093410428u, 261151u),
    uvec2(3791420540u, 520255u),
    uvec2(2155641982u, 516351u),
    uvec2(3964030u, 1033215u),
    uvec2(3964028u, 1017855u),
    uvec2(4062332u, 1019903u),
    uvec2(4193404u, 2035695u),
    uvec2(4192508u, 2035615u),
    uvec2(4190712u, 2035487u),
    uvec2(2155856376u, 2035487u),
    uvec2(3791586288u, 2035487u),
    uvec2(4093513712u, 2068255u),
    uvec2(4294459360u, 2068255u),
    uvec2(4292935648u, 2068255u),
    uvec2(4290904032u, 1036063u),
    uvec2(1072168928u, 1044255u),
    uvec2(536869856u, 524063u),
    uvec2(134210528u, 524063u),
    uvec2(2181023712u, 261919u),
    uvec2(3774842816u, 130975u),
    uvec2(4164816832u, 65439u),
    uvec2(4227866560u, 16271u),
    uvec2(4278206336u, 3971u),
    uvec2(4290838272u, 4032u),
    uvec2(2147483392u, 2016u),
    uvec2(536870400u, 2032u),
    uvec2(134215680u, 1016u),
    uvec2(4294963200u, 1023u),
    uvec2(4294950912u, 511u),
    uvec2(4290772992u, 255u),
    uvec2(4278190080u, 127u),
    uvec2(4261412864u, 31u),
    uvec2(4026531840u, 1u)
);
float logoAlpha(vec2 uv) {
    vec2 p = uv * vec2(53.0, 54.0);
    ivec2 cell = ivec2(floor(p + 0.5));
    if (cell.x < 0 || cell.x >= 53 || cell.y < 0 || cell.y >= 54) return 0.0;
    uint bits = logoRows[cell.y][cell.x / 32];
    float occupied = float((bits >> uint(cell.x % 32)) & 1u);
    float aa = max(fwidth(p.x), fwidth(p.y)) * 0.5;
    return occupied * (1.0 - smoothstep(0.34 - aa, 0.34 + aa, length(p - vec2(cell))));
}
float hash21(vec2 p) {
    return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453);
}
float noise(vec2 p) {
    vec2 i = floor(p), f = fract(p);
    f = f * f * (3.0 - 2.0 * f);
    return mix(mix(hash21(i), hash21(i + vec2(1, 0)), f.x),
                mix(hash21(i + vec2(0, 1)), hash21(i + 1.0), f.x), f.y);
}
void mainImage(out vec4 fragColor, in vec2 fragCoord) {
    vec2 uv = vec2(fragCoord.x, iResolution.y - fragCoord.y) / iResolution.xy;
    // Cursor cell height tracks Retina/font scaling; Ghostty has no DPI uniform.
    float Scale = clamp(iCurrentCursor.w / 20.0, 1.0, 3.0);
    vec2 Resolution = iResolution.xy;
    float Time = iTime;
    vec4 terminal = terminalAt(uv);
    vec2 size = Resolution / max(Scale, 1.0);
    vec2 px = uv * size;
    vec2 edge = min(px, size - px);
    vec3 amber = vec3(240, 179, 74) / 255.0;
    vec3 cyan = vec3(59, 224, 200) / 255.0;
    vec3 ink = vec3(7, 7, 10) / 255.0;

    // Codex draws full-width rectangular prompt/message backgrounds. Round
    // their visible corners in the compositor without changing TUI input or
    // touching glyphs, colored diffs, or selection colors.
    const float radius = 10.0;
    float high = max(terminal.r, max(terminal.g, terminal.b));
    float low = min(terminal.r, min(terminal.g, terminal.b));
    // Support both linear and sRGB terminal render surfaces.
    bool panelPixel = high > 0.009 && high < 0.26 && high - low < 0.035;
    if (panelPixel && edge.x < radius) {
        float verticalDistance = radius;
        vec3 outside = ink;

        for (int d = 1; d <= 10; d++) {
            vec2 delta = vec2(0, float(d) / size.y);
            vec3 above = terminalAt(uv - delta).rgb;
            vec3 below = terminalAt(uv + delta).rgb;
            // Bright text cannot be mistaken for a panel boundary.
            float aboveHigh = max(above.r, max(above.g, above.b));
            float belowHigh = max(below.r, max(below.g, below.b));
            if (aboveHigh < high * 0.55 || belowHigh < high * 0.55) {
                outside = aboveHigh < belowHigh ? above : below;
                verticalDistance = min(verticalDistance, float(d));
            }
        }
        vec2 corner = max(vec2(radius - edge.x, radius - verticalDistance), 0.0);
        float coverage = 1.0 - smoothstep(radius - 0.7, radius + 0.7, length(corner));
        terminal.rgb = mix(outside, terminal.rgb, coverage);
    }

    // Only decorate background pixels; retain text, selections and diffs.
    float distanceFromInk = length(terminal.rgb - ink);
    float backgroundMask = 1.0 - smoothstep(0.025, 0.14, distanceFromInk);
    vec3 decoration = vec3(0.0);

    // The native idle blossom occupied about 304 logical pixels at the tested
    // default font size. Keep it at 25% width/height, centered in the lower-right
    // quarter. It is a persistent background mark, never painted over glyphs.
    const float originalMarkSize = 304.0;
    const float markScale = 0.25;
    float markSize = min(originalMarkSize * markScale, min(size.x, size.y) * 0.20);
    vec2 markCenter = size * vec2(0.75, 0.75);
    // Reserve the composer/footer on shorter windows so the mark stays whole.
    markCenter.y = min(markCenter.y, size.y - 112.0 - markSize * 0.5 - 12.0);
    vec2 markUV = (px - markCenter) / markSize + 0.5;
    if (markCenter.y - markSize * 0.5 >= size.y * 0.5 && all(greaterThanEqual(markUV, vec2(0.0))) && all(lessThanEqual(markUV, vec2(1.0)))) {
        float markAlpha = logoAlpha(markUV);
        decoration += vec3(0.16, 0.17, 0.20) * markAlpha;
    }

    // Two amber rails and turquoise HUD corner brackets.
    float verticalRail = 1.0 - smoothstep(0.6, 1.6, abs(edge.x - 7.0));
    float horizontalRail = 1.0 - smoothstep(0.6, 1.6, abs(edge.y - 7.0));
    float corners = saturate(verticalRail * (1.0 - step(49.0, edge.y)) +
                            horizontalRail * (1.0 - step(49.0, edge.x)));
    decoration += cyan * corners * 0.8;
    decoration += amber * verticalRail * 0.16;

    // Quantized, rising flames stay within 48 logical pixels of the sides.
    vec2 cell = floor(px / 3.0) * 3.0;
    float animationTime = Time;
    #ifdef W1_STILL
        animationTime = 0.0;
    #endif
    float flow = noise(vec2(cell.y * 0.026 + animationTime * 0.8, cell.x * 0.04));
    flow += 0.45 * noise(vec2(cell.y * 0.06 + animationTime * 1.2, cell.x * 0.08));
    float tongue = 8.0 + 32.0 * flow;
    float flame = (1.0 - smoothstep(tongue - 9.0, tongue + 2.0, edge.x));
    flame *= smoothstep(9.0, 20.0, edge.x);
    flame *= 0.24 + 0.10 * sin(cell.y * 0.03 + animationTime);
    decoration += mix(amber, cyan, step(0.5, uv.x)) * flame;

    // Faint circuit grid in the outer gutter only.
    float grid = (1.0 - step(1.0, mod(px.y, 24.0))) * (1.0 - smoothstep(30.0, 70.0, edge.x));
    decoration += cyan * grid * 0.07;
    fragColor = vec4(saturate(terminal.rgb + decoration * backgroundMask), terminal.a);
}
