"""Port the shared visual math to Ghostty GLSL and embed the logo dot mask."""
from pathlib import Path
import re
import xml.etree.ElementTree as ET

root = Path(__file__).resolve().parents[1]
svg = ET.parse(root / 'assets/codex-mark.svg').getroot()
width, height = [int(v) for v in svg.attrib['viewBox'].split()[2:]]
rows = [[0, 0] for _ in range(height)]
for circle in svg.findall('.//{http://www.w3.org/2000/svg}circle'):
    x, y = int(circle.attrib['cx']), int(circle.attrib['cy'])
    rows[y][x // 32] |= 1 << (x % 32)
mask = ',\n'.join(f'    uvec2({a}u, {b}u)' for a, b in rows)
header = '''// Magik Terminal for Codex (By W1d0wm4k3r). MIT visual code.
// Generated by tools/build-macos-shader.py from windows/magik.hlsl.
// Logo dot data derives from Apache-2.0 Codex source; see assets/README.md.
// Ghostty supplies iChannel0, iResolution, iTime, and iCurrentCursor.
float saturate(float v) { return clamp(v, 0.0, 1.0); }
vec3 saturate(vec3 v) { return clamp(v, 0.0, 1.0); }
vec4 terminalAt(vec2 topUV) {
    return texture(iChannel0, vec2(topUV.x, 1.0 - topUV.y));
}
'''
header += f'const uvec2 logoRows[{height}] = uvec2[{height}](\n{mask}\n);\n'
header += f'''float logoAlpha(vec2 uv) {{
    vec2 p = uv * vec2({width}.0, {height}.0);
    ivec2 cell = ivec2(floor(p + 0.5));
    if (cell.x < 0 || cell.x >= {width} || cell.y < 0 || cell.y >= {height}) return 0.0;
    uint bits = logoRows[cell.y][cell.x / 32];
    float occupied = float((bits >> uint(cell.x % 32)) & 1u);
    float aa = max(fwidth(p.x), fwidth(p.y)) * 0.5;
    return occupied * (1.0 - smoothstep(0.34 - aa, 0.34 + aa, length(p - vec2(cell))));
}}
'''
source = (root / 'windows/magik.hlsl').read_text()
source = source[source.index('float hash21'):]
source = source.replace('float4 main(float4 pos : SV_POSITION, float2 uv : TEXCOORD) : SV_TARGET {',
'''void mainImage(out vec4 fragColor, in vec2 fragCoord) {
    vec2 uv = vec2(fragCoord.x, iResolution.y - fragCoord.y) / iResolution.xy;
    // Cursor cell height tracks Retina/font scaling; Ghostty has no DPI uniform.
    float Scale = clamp(iCurrentCursor.w / 20.0, 1.0, 3.0);
    vec2 Resolution = iResolution.xy;
    float Time = iTime;''')
source = re.sub(r'shaderTexture.Sample\(samplerState, ([^)]+)\)', r'terminalAt(\1)', source)
source = source.replace('codexMark.Sample(samplerState, markUV).a', 'logoAlpha(markUV)')
for old, new in [('float2', 'vec2'), ('float3', 'vec3'), ('float4', 'vec4'),
                 ('frac(', 'fract('), ('lerp(', 'mix('), ('fmod(', 'mod('), ('[unroll]', '')]:
    source = source.replace(old, new)
source = source.replace('vec3 decoration = 0;', 'vec3 decoration = vec3(0.0);')
source = source.replace('all(markUV >= 0.0) && all(markUV <= 1.0)',
                        'all(greaterThanEqual(markUV, vec2(0.0))) && all(lessThanEqual(markUV, vec2(1.0)))')
source = source.replace('return vec4(saturate(terminal.rgb + decoration * backgroundMask), terminal.a);',
                        'fragColor = vec4(saturate(terminal.rgb + decoration * backgroundMask), terminal.a);')
(root / 'macos').mkdir(exist_ok=True)
(root / 'macos/magik.glsl').write_text('\n'.join(line.rstrip() for line in (header + source).splitlines()) + '\n', encoding='utf-8', newline='\n')
print('Built macos/magik.glsl with embedded Codex dot mask.')
